-- ==================================================
-- 03 Stage Tables
-- Enterprise Retail Analytics Pipeline
-- ==================================================

-- Step-4: Create a file format using the FILE FORMAT command to describe the format of the file to be imported
CREATE OR REPLACE FILE FORMAT CSV_SKIP_HEADER
type = 'CSV'
field_delimiter = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
skip_header = 1;

-- Step-5: Create Tables

CREATE OR REPLACE TABLE STAGE_CHANNEL (
    CHANNELID NUMBER(38,0),
    CHANNELCATEGORYID NUMBER(38,0),
    CHANNEL VARCHAR(255),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0)
);

CREATE OR REPLACE TABLE STAGE_CHANNELCATEGORY (
    CHANNELCATEGORYID NUMBER(38,0),
    CHANNELCATEGORY VARCHAR(255),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0)
);

CREATE OR REPLACE TABLE STAGE_CUSTOMER (
    CUSTOMERID VARCHAR(255),
    SUBSEGMENTID NUMBER(38,0),
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    GENDER VARCHAR(255),
    EMAILADDRESS VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    STATEPROVINCE VARCHAR(255),
    COUNTRY VARCHAR(255),
    POSTALCODE NUMBER(38,0),
    PHONENUMBER VARCHAR(255),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0)
);

CREATE OR REPLACE TABLE STAGE_PRODUCT (
    PRODUCTID NUMBER(38,0),
    PRODUCTTYPEID NUMBER(38,0),
    PRODUCT VARCHAR(255),
    COLOR VARCHAR(255),
    STYLE VARCHAR(255),
    UNITOFMEASUREID NUMBER(38,0),
    WEIGHT NUMBER(38,2),
    PRICE NUMBER(38,2),
    COST NUMBER(38,2),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0),
    WHOLESALEPRICE NUMBER(38,2)
);

CREATE OR REPLACE TABLE STAGE_PRODUCTCATEGORY (
    PRODUCTCATEGORYID NUMBER(38,0),
    PRODUCTCATEGORY VARCHAR(255),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0)
);

CREATE OR REPLACE TABLE STAGE_PRODUCTTYPE (
    PRODUCTTYPEID NUMBER(38,0),
    PRODUCTCATEGORYID NUMBER(38,0),
    PRODUCTTYPE VARCHAR(255),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0)
);

CREATE OR REPLACE TABLE STAGE_RESELLER (
    RESELLERID VARCHAR(255),
    CONTACT VARCHAR(255),
    EMAILADDRESS VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    STATEPROVINCE VARCHAR(255),
    COUNTRY VARCHAR(255),
    POSTALCODE NUMBER(38,0),
    PHONENUMBER VARCHAR(255),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0),
    RESELLERNAME VARCHAR(255)
);

CREATE OR REPLACE TABLE STAGE_SALESDETAIL (
    SALESDETAILID NUMBER(38,0),
    SALESHEADERID NUMBER(38,0),
    PRODUCTID NUMBER(38,0),
    SALESQUANTITY NUMBER(38,0),
    SALESAMOUNT NUMBER(38,2),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0)
);

CREATE OR REPLACE TABLE STAGE_SALESHEADER (
    SALESHEADERID NUMBER(38,0),
    DATE DATE,
    CHANNELID NUMBER(38,0),
    STOREID NUMBER(38,0),
    CUSTOMERID VARCHAR(255),
    RESELLERID VARCHAR(255),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0)
);

CREATE OR REPLACE TABLE STAGE_STORE (
    STOREID NUMBER(38,0),
    SUBSEGMENTID NUMBER(38,0),
    STORENUMBER NUMBER(38,0),
    STOREMANAGER VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    STATEPROVINCE VARCHAR(255),
    COUNTRY VARCHAR(255),
    POSTALCODE NUMBER(38,0),
    PHONENUMBER VARCHAR(255),
    CREATEDDATE DATE,
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE DATE,
    MODIFIEDBY NUMBER(38,0)
);

CREATE OR REPLACE TABLE STAGE_TARGET_PRODUCT (
    PRODUCTID NUMBER(38,0),
    PRODUCT VARCHAR(255),
    YEAR NUMBER(38,0),
    SALESQUANTITYTARGET NUMBER(38,0)
);

CREATE OR REPLACE TABLE STAGE_TARGET_CHANNEL_RESELLER_STORE (
    YEAR NUMBER(38,0),
    CHANNELNAME VARCHAR(255),
    TARGETNAME VARCHAR(255),
    TARGETSALESAMOUNT NUMBER(38,2)
