-- ==================================================
-- 04 Load Stage Tables
-- Enterprise Retail Analytics Pipeline
-- ==================================================

-- Note: The original worksheet included an old Star Wars COPY INTO example from a previous exercise.
-- It was removed from this public portfolio version to keep the script focused on the retail analytics pipeline.

-- Step-6: Copy Data into Stage > Table
COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_CHANNEL" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CHANNEL_STAGE"/Channel.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_CHANNELCATEGORY" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CHANNEL_CATEGORY_STAGE"/channelcategory.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_CUSTOMER" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CUSTOMER_STAGE"/Customer.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_PRODUCT" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."PRODUCT_STAGE"/Product.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_PRODUCTCATEGORY" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."PRODUCT_CATEGORY_STAGE"/ProductCategory.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_PRODUCTTYPE" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."PRODUCT_TYPE_STAGE"/ProductType.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_RESELLER" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."RESELLER_STAGE"/Reseller.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_SALESDETAIL" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."SALES_DETAIL_STAGE"/SalesDetail.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_SALESHEADER" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."SALES_HEADER_STAGE"/SalesHeader_New.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_STORE" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."STORE_STAGE"/Store.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_TARGET_PRODUCT" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."TARGET_DATA_PRODUCT_STAGE"/Target Data - Product.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;

COPY INTO "ENTERPRISE_COMMERCE_DW"."PUBLIC"."STAGE_TARGET_CHANNEL_RESELLER_STORE" FROM '@"ENTERPRISE_COMMERCE_DW"."PUBLIC"."TARGET_DATA_CHANNEL_STAGE"/Target Data - Channel Reseller and Store.csv' 
FILE_FORMAT = '"ENTERPRISE_COMMERCE_DW"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE ;
